apiVersion: v1
kind: Service
metadata:
  name: migration-service
spec:
  selector:
    app: migration-service
  type: ClusterIP # For internal communication within the cluster
  ports:
    - protocol: TCP
      port: 80 # External port (can be different from container port)
      targetPort: 8081 # Port exposed by the container
